[language-server.steel-language-server]
command = "steel-language-server"
args = []

[[language]]
name = "scheme"
formatter = { command = "raco", args = ["fmt", "-i"] }
auto-format = true
language-servers = [ "steel-language-server" ]

[[language]]
name = "c"
indent = { tab-width = 4, unit = " " }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = " " } 

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "t" } 
